name = "sEMTor"
uuid = "3aa00187-1793-4006-8dbf-b0a7dd891f4e"
authors = ["Steffen Plunder <steffen.plunder@web.de> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
